apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: commodo-{{.Values.environment}}
  name: commodo-{{.Values.environment}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: commodo-{{.Values.environment}}
    spec:
      containers:
      - env:
        - name: REACT_APP_INFURA_URI
          value: {{.Values.react_app_infura_uri}}
        - name: REACT_APP_CHAIN_ID
          value: "{{.Values.react_app_chain_id}}"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: commodo-{{.Values.environment}}
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "1024Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      restartPolicy: Always
status: {}
