apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: commodo
  name: commodo
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: commodo
status:
  loadBalancer: {}
